### ISSUE TITLE
Don't close all existing connections when closing the server

### ISSUE THREAD

**Issue by shaharmor** [uWebSockets/bindings#12]
Hi,

Its not possible to stop the server from listening for new connections without also closing existing connections.

Any chance to add support for it?

P.S.
It may be possible by accessing the `.httpServer` property, but not sure its the way to go

**Comment by lll000111** [comment]
If you pass in your own node.js http server, wouldn't you be able to control it?

**Comment by alexhultman** [comment]
Yes exactly.
