### ISSUE TITLE
API inconsistency

### ISSUE THREAD

**Issue by lll000111** [uWebSockets/bindings#13]
## Problem description:

I can subscribe to `message` events in two ways:

1)
```javascript
ws.on('message', message => {
    // message is a string or an ArrayBuffer
});
```

2)
```javascript
ws.onmessage = message => {
    // message is an object {data: string | ArrayBuffer}
};
```
The first option is implemented through https://github.com/uWebSockets/bindings/blob/master/nodejs/src/uws.js#L149

The second option is achieved in this file and line: https://github.com/uWebSockets/bindings/blob/master/nodejs/src/uws.js#L102

The second option also is the official WebSocket API.

So the first option seems to be wrong: When I look at [the WS API under "Event: 'message'"](https://github.com/websockets/ws/blob/master/doc/ws.md#event-message) I see the object with the `data` property, and [the WebSocket example on MDN under "Example"](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) has this code:

```javascript
// Listen for messages
socket.addEventListener('message', function (event) {
    console.log('Message from server', event.data);
});
```

As far as I can see when I subscribe to the `message` event I should get the exact same result, an object with a `data` property holding the message data, regardless of if I use normal event subscription or the `onmessage` setter.

The two different calls are in file https://github.com/uWebSockets/bindings/blob/master/nodejs/src/uws.js in lines #56 for `on('message',...)` and #101 for `onmessage` respectively.

The official Javascript WebSocket API is found on MDN, scroll to "Attributes": https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

You can also see it on https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications in the example under "Receiving messages from the server".

The same issue exists for the `close` event, see lines #63 and #120, which use different call methods for the callback, one with two arguments, one with an object with two properties (the latter is the correct WebSocket API according to MDN).

You can also see it in the official standards document, link to the relevant part for `MessageEvent`: https://html.spec.whatwg.org/multipage/comms.html#messageevent

## Proposed fixes:

To fix this for the `message` event change line #56 to

```javascript
    webSocket.internalOnMessage({data: message});
```

To fix this for the `close` event change line #63 to

```javascript
    webSocket.internalOnClose({code: code, reason: message});
```

The same should probably be done for the respective events in the `emit()` method starting at line #135.

Events `ping` and `pong` are different from the `ws` API too, same object as `message` events, but I didn't see anything about those in the standard.

The example code in https://github.com/uWebSockets/bindings/blob/master/nodejs/README.md also needs to be changed if the changes I propose above are implemented.

**Comment by alexhultman** [comment]
I'm 95% sure things are correct as is.

**Comment by lll000111** [comment]
Uhm... I included links to the official API.

**Comment by alexhultman** [comment]
uws <-> ws are compatible enough to have users swap easily. There is no relation between uws and those links you posted. Besides, this project runs on many servers already so had it been this broken we would have known by now.

**Comment by lll000111** [comment]
I said I included links to the *official Javascript WebSocket API* :-)

I don't care about WS, I included those references only because you did.

**Comment by alexhultman** [comment]
Did you care to test ws? Like said, I'm 95% sure things are just like they are in ws. Please test how ws differs between onmessage and on('message'). uws relates to ws, nothing else.

**Comment by lll000111** [comment]
> There is no relation between uws and those links you posted. 

I posted this:

https://github.com/websockets/ws/blob/master/doc/ws.md#event-message

This shows the method #1 to attach a listener. The other one is described at

https://github.com/websockets/ws/blob/master/doc/ws.md#websocketonmessage

Both send the same argument to the callbacks, so the exact same callback function can be used either way.

That, and the official API that I keep coming back to.... If you don't care about the official API just say so then I'll know to stop.

**Comment by alexhultman** [comment]
You are very persistent so I actually took the time to extra check this myself (something *you* should have done by now). Current behavior is *correct and follows the behavior of ws*.

**Comment by lll000111** [comment]
I asked about the official API. You did not answer yet.

**Comment by alexhultman** [comment]
I will permanently ban you if you respond after this post.

**Comment by lll000111** [comment]
Alex, I BEG you, please just tell me why the API does not matter. I'm just a darn user, I would like to understand your reasoning! Is this such a horrible question?

**Comment by alexhultman** [comment]
Look, try and listen: uws is a server. It implements the ws behavior. This is done, so that many users can swap. ws is very popular, so having an interface similar is important to leverage the popularity of ws.

This has been shown to already work. There are many users that have swapped from ws to uws (and back in some cases). That is what the goal is: easy swapping between the most popular module, and uws.

You are referring to the *browser* API, which differs from how ws works. uws is not a browser, it is a server. It follows a different design that is decided by the ws module. There is no "official" server interface for WebSockets.

If I could ignore the ws interface, I would. I know some much more efficient ones that I would much rather implement but I simply cannot do that because of how valuable the compatibility with ws is.
