### ISSUE TITLE
Don't hardcode SecKey length 

### ISSUE THREAD

**Issue by bkniffler** [uWebSockets/bindings#15]
https://github.com/uWebSockets/bindings/blob/b0f4e97e8d85be820721c2af28104953cb24a384/nodejs/src/uws.js#L494

Currently the key is fixed to 24 characters. I've had some trouble using uws with the official arduino http/websocket client, since it generates keys of lesser length (https://github.com/arduino-libraries/ArduinoHttpClient/blob/master/src/WebSocketClient.cpp#L39). I'm not sure about the specifications, but as far as I understand, there is no specific required length. 

Could you elaborate if the fixed length is really necessary?

**Comment by alexhultman** [comment]
I've never seen lengths other than 24 but I don't know for sure if this is a standard. In any case, you should get this fixed in the Arduino client because not using 24 length but 21 instead is just stupid and not the de-facto length. It makse no sense to deviate from the norm just because it might technically be possible.

**Comment by bkniffler** [comment]
I completely agree that a library should always pick the norm as default value. But then again, since there is no fixed specification (assuming there isn't), why would you want to hardcode the length?

**Comment by alexhultman** [comment]
Because it can only handle 24 bytes input right now.

**Comment by bkniffler** [comment]
Oh well, completely ignored the fact that this isn't a pure JS implementation but a wrapper around a native lib, which makes this more complicated. So the best way to fix this is on the clients side. I'll close this issue.

**Comment by lpinca** [comment]
From https://tools.ietf.org/html/rfc6455#section-4.1

> The request MUST include a header field with the name
        |Sec-WebSocket-Key|.  The value of this header field MUST be a
        nonce consisting of a randomly selected 16-byte value that has
        been base64-encoded (see Section 4 of [RFC4648]).  The nonce
        MUST be selected randomly for each connection.

so checking that the length is`24` (base64-encoded) is not wrong.
