### ISSUE TITLE
Pre-compile win/mac/linux builds, then separate them in namespaces.

### ISSUE THREAD

**Issue by clusteratlas** [uWebSockets/bindings#9]
Can't the binaries really be pre-compiled? The NPM registry have 100mb limit for the package anyways, highly doubt the binaries would even reach it.

Hope we can have it like how Faye does it (very clean imo)
https://faye.jcoglan.com/
https://faye.jcoglan.com/node.html

Much better too if we can have a compiled / browserified version of it hosted on CDNjs.

---

PS: Instead of working on top of current wrapper, We second nuking the hell out of this from the ground up.

https://github.com/uWebSockets/uWebSockets/issues/381

**Comment by lll000111** [comment]
In addition, quoting from the top README (very bottom):

> If this fails it will silently fall back to using the precompiled binaries. NPM installation will never fail

That's not true, I just tried to install it and it failed. So where are those "precompiled binaries" mentioned in the short top-level README?

**Comment by alexhultman** [comment]
I don't understand you.
